spring.application.name=ms-usuarios-accesos
spring.datasource.url=jdbc:mysql://localhost:3308/ms_usuarios_accesos?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
server.port=8080
JPA / Hibernate

#Sincroniza automáticamente tu código de Java con tu base de datos.
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



