spring.application.name=ms-gestion-clientes
server.port=8084

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3308/ms-gestion-clientes?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Client
# Asegúrate de que el puerto coincida con el de tu servidor Eureka (usualmente 8761)
eureka.client.service-url.default-zone=http://localhost:8761/eureka/

# Compatibilidad de versiones
spring.cloud.compatibility-verifier.enabled=false