# Nombre del Gateway
spring.application.name=api-gateway

# Puerto
server.port=8080

# Conexión a Eureka (CORREGIDO: default-zone)
eureka.client.service-url.default-zone=http://localhost:8761/eureka/

# Configuración de descubrimiento automático
# Esto permite que tus microservicios sean accesibles como: /ms-devoluciones/ruta-del-servicio
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Bypass de compatibilidad (para evitar el error de versión que veníamos viendo)
spring.cloud.compatibility-verifier.enabled=false