# ==========================================
# AREA 1: CONFIGURACIÓN BÁSICA
# ==========================================
server.port=8081
spring.application.name=ms-catalogo-repuestos

# ==========================================
# AREA 2: CONEXIÓN Y PERSISTENCIA
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3308/ms-catalogo_repuestos?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# AREA 3: VÍNCULO CON LA ARQUITECTURA (Eureka)
# ==========================================
# URL donde Eureka espera recibir el registro de tus microservicios
eureka.client.service-url.default-zone=http://localhost:8761/eureka/

# Compatibilidad para evitar errores de versión
spring.cloud.compatibility-verifier.enabled=false

# NOTA: Asegúrate de NO tener comentado el registro en Eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true